//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tagging {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class TagDatabaseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TagDatabaseSettings defaultInstance = ((TagDatabaseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TagDatabaseSettings())));
        
        public static TagDatabaseSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<studies />")]
        public global::System.Xml.XmlDocument DatabaseXml {
            get {
                return ((global::System.Xml.XmlDocument)(this["DatabaseXml"]));
            }
            set {
                this["DatabaseXml"] = value;
            }
        }
    }
}
