//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportFromBitmap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportFromBitmap.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import (non-Dicom).
        /// </summary>
        internal static string MenuImportFromBitmap {
            get {
                return ResourceManager.GetString("MenuImportFromBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating files ....
        /// </summary>
        internal static string MessageEnumeratingFiles {
            get {
                return ResourceManager.GetString("MessageEnumeratingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting image {0} of {1}.
        /// </summary>
        internal static string MessageFormatConvertingToDicom {
            get {
                return ResourceManager.GetString("MessageFormatConvertingToDicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} of {1} images..
        /// </summary>
        internal static string MessageFormatReportSuccess {
            get {
                return ResourceManager.GetString("MessageFormatReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import any of the {0} images..
        /// </summary>
        internal static string MessageFormatTotalFailure {
            get {
                return ResourceManager.GetString("MessageFormatTotalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another import is currently running.  Please wait until it completes..
        /// </summary>
        internal static string MessageImportAlreadyRunning {
            get {
                return ResourceManager.GetString("MessageImportAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are invalid characters..
        /// </summary>
        internal static string MessageInvalidCharacters {
            get {
                return ResourceManager.GetString("MessageInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import the selected items because the Local Data Store service is not running.
        ///Please ensure the ClearCanvas server is running or contact your system administrator for assistance..
        /// </summary>
        internal static string MessageLocalDataStoreServiceMustBeRunning {
            get {
                return ResourceManager.GetString("MessageLocalDataStoreServiceMustBeRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accession number must be entered (1-16 characters)..
        /// </summary>
        internal static string MessageMustEnterAccession {
            get {
                return ResourceManager.GetString("MessageMustEnterAccession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient id must be entered (1-64 characters)..
        /// </summary>
        internal static string MessageMustEnterPatientId {
            get {
                return ResourceManager.GetString("MessageMustEnterPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient&apos;s first and last name must be entered..
        /// </summary>
        internal static string MessageMustEnterPatientName {
            get {
                return ResourceManager.GetString("MessageMustEnterPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files have been selected for import..
        /// </summary>
        internal static string MessageNothingToImport {
            get {
                return ResourceManager.GetString("MessageNothingToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The study description must not exceed 64 characters..
        /// </summary>
        internal static string MessageStudyDescriptionTooLong {
            get {
                return ResourceManager.GetString("MessageStudyDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while importing the selected images.  Please see the logs for more details..
        /// </summary>
        internal static string MessageUnexpectedError {
            get {
                return ResourceManager.GetString("MessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Images (non-Dicom).
        /// </summary>
        internal static string TitleImportingImages {
            get {
                return ResourceManager.GetString("TitleImportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Images (non-Dicom).
        /// </summary>
        internal static string TitleImportNonDicom {
            get {
                return ResourceManager.GetString("TitleImportNonDicom", resourceCulture);
            }
        }
    }
}
