//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nullstack.ClearCanvas.DevTools.View.WinForms {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ViewSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewSettings defaultInstance = ((ViewSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewSettings())));
        
        public static ViewSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoScrollToEnd {
            get {
                return ((bool)(this["AutoScrollToEnd"]));
            }
            set {
                this["AutoScrollToEnd"] = value;
            }
        }
    }
}
