//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nullstack.ClearCanvas.DevTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nullstack.ClearCanvas.DevTools.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string fmCommandName {
            get {
                return ResourceManager.GetString("fmCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0}.
        /// </summary>
        internal static string fmCurrentCommandName {
            get {
                return ResourceManager.GetString("fmCurrentCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0:X8}.
        /// </summary>
        internal static string fmHashcode {
            get {
                return ResourceManager.GetString("fmHashcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string fmIndex {
            get {
                return ResourceManager.GetString("fmIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count = {0}.
        /// </summary>
        internal static string fmListDescription {
            get {
                return ResourceManager.GetString("fmListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Action Models.
        /// </summary>
        internal static string mnActionModels {
            get {
                return ResourceManager.GetString("mnActionModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advance Log.
        /// </summary>
        internal static string mnAdvanceLog {
            get {
                return ResourceManager.GetString("mnAdvanceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &amp;Settings.
        /// </summary>
        internal static string mnApplicationSettings {
            get {
                return ResourceManager.GetString("mnApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bad Files.
        /// </summary>
        internal static string mnBadFiles {
            get {
                return ResourceManager.GetString("mnBadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Command History Inspector.
        /// </summary>
        internal static string mnCommandHistoryInspector {
            get {
                return ResourceManager.GetString("mnCommandHistoryInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Common.
        /// </summary>
        internal static string mnCommon {
            get {
                return ResourceManager.GetString("mnCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Configure.
        /// </summary>
        internal static string mnConfigure {
            get {
                return ResourceManager.GetString("mnConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Data Store.
        /// </summary>
        internal static string mnDataStore {
            get {
                return ResourceManager.GetString("mnDataStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        internal static string mnDebug {
            get {
                return ResourceManager.GetString("mnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string mnDelete {
            get {
                return ResourceManager.GetString("mnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Error.
        /// </summary>
        internal static string mnError {
            get {
                return ResourceManager.GetString("mnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Executable.
        /// </summary>
        internal static string mnExecutable {
            get {
                return ResourceManager.GetString("mnExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fatal.
        /// </summary>
        internal static string mnFatal {
            get {
                return ResourceManager.GetString("mnFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File Store.
        /// </summary>
        internal static string mnFileStore {
            get {
                return ResourceManager.GetString("mnFileStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Folders.
        /// </summary>
        internal static string mnFolders {
            get {
                return ResourceManager.GetString("mnFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Info.
        /// </summary>
        internal static string mnInfo {
            get {
                return ResourceManager.GetString("mnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Le&amp;vel.
        /// </summary>
        internal static string mnLogLevel {
            get {
                return ResourceManager.GetString("mnLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logs.
        /// </summary>
        internal static string mnLogs {
            get {
                return ResourceManager.GetString("mnLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Log &amp;Marker.
        /// </summary>
        internal static string mnMarkLogPosition {
            get {
                return ResourceManager.GetString("mnMarkLogPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monitor.
        /// </summary>
        internal static string mnMonitor {
            get {
                return ResourceManager.GetString("mnMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string mnOpen {
            get {
                return ResourceManager.GetString("mnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Plugins.
        /// </summary>
        internal static string mnPlugins {
            get {
                return ResourceManager.GetString("mnPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser&amp;vice.
        /// </summary>
        internal static string mnService {
            get {
                return ResourceManager.GetString("mnService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser&amp;vice Log.
        /// </summary>
        internal static string mnServiceLog {
            get {
                return ResourceManager.GetString("mnServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Synchronize Device XMLs.
        /// </summary>
        internal static string mnSynchronizeDeviceXmls {
            get {
                return ResourceManager.GetString("mnSynchronizeDeviceXmls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tail.
        /// </summary>
        internal static string mnTail {
            get {
                return ResourceManager.GetString("mnTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Warn.
        /// </summary>
        internal static string mnWarn {
            get {
                return ResourceManager.GetString("mnWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Workstation Log.
        /// </summary>
        internal static string mnWorkstationLog {
            get {
                return ResourceManager.GetString("mnWorkstationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action model has been deleted. You need to restart the application to see the changes and recreate the action model..
        /// </summary>
        internal static string msgActionModelDeleted {
            get {
                return ResourceManager.GetString("msgActionModelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete the action model?.
        /// </summary>
        internal static string msgConfirmDeleteActionModel {
            get {
                return ResourceManager.GetString("msgConfirmDeleteActionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete all user settings files for ClearCanvas.Desktop.Executable.exe?.
        /// </summary>
        internal static string msgConfirmDeleteAllUserSettings {
            get {
                return ResourceManager.GetString("msgConfirmDeleteAllUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command History Inspector.
        /// </summary>
        internal static string szCommandHistoryInspector {
            get {
                return ResourceManager.GetString("szCommandHistoryInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        internal static string szDevTools {
            get {
                return ResourceManager.GetString("szDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Log.
        /// </summary>
        internal static string szServiceLog {
            get {
                return ResourceManager.GetString("szServiceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation Log.
        /// </summary>
        internal static string szWorkstationLog {
            get {
                return ResourceManager.GetString("szWorkstationLog", resourceCulture);
            }
        }
    }
}
